const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const appSource = fs.readFileSync(path.join(__dirname, "..", "assets", "app.js"), "utf8");
const cssSource = fs.readFileSync(path.join(__dirname, "..", "assets", "styles.css"), "utf8");
const indexSource = fs.readFileSync(path.join(__dirname, "..", "index.html"), "utf8");
const captureSource = fs.readFileSync(path.join(__dirname, "..", "scripts", "capture-readme-screenshots.js"), "utf8");
const verifySource = fs.readFileSync(path.join(__dirname, "..", "scripts", "verify-local-performance.js"), "utf8");

function cssBlock(selector) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
  const match = cssSource.match(new RegExp(`${escaped}\\s*\\{[^}]*\\}`, "u"));
  assert.ok(match, `CSS block not found: ${selector}`);
  return match[0];
}

test("mobile information architecture exposes one query center and a one-row toolbar", () => {
  assert.match(indexSource, /id="querySearchForm"[\s\S]*id="queryInput"[\s\S]*name="searchField" value="title"[\s\S]*name="searchField" value="artist"/u);
  assert.doesNotMatch(indexSource, /id="openSearchButton"|id="openFilterButton"|id="desktopFilterButton"/u);
  assert.match(indexSource, /id="mobileBottomNav"[\s\S]*data-view="songRank"[\s\S]*data-view="artistRank"[\s\S]*data-view="songAz"[\s\S]*data-view="vtuberRank"[\s\S]*data-view="videos"/u);
  assert.match(indexSource, /class="[^"]*view-mode[^"]*"[\s\S]*data-view="songRank"[\s\S]*data-view="artistRank"[\s\S]*data-view="vtuberRank"[\s\S]*data-view="songAz"[\s\S]*data-view="videos"/u);
  assert.match(indexSource, /data-view="vtuberRank"[\s\S]*<span>频道<\/span>/u);
  assert.match(indexSource, /class="query-field-menu-panel"[\s\S]*name="searchField" value="channel"[\s\S]*name="searchField" value="video"[\s\S]*全不选时搜索全部字段/u);
  assert.doesNotMatch(indexSource, /id="searchSuggestions"/u);
  assert.match(indexSource, /id="queryInput" type="search"[\s\S]*id="clearQueryButton"/u);
  assert.match(cssSource, /\.query-search-form input\[type="search"\]\s*\{[\s\S]*-webkit-appearance: none;[\s\S]*appearance: textfield;/u);
  assert.match(cssSource, /\.query-search-form input\[type="search"\]::-webkit-search-cancel-button,[\s\S]*\.query-search-form input\[type="search"\]::-webkit-search-decoration,[\s\S]*\.query-search-form input\[type="search"\]::-webkit-search-results-button,[\s\S]*\.query-search-form input\[type="search"\]::-webkit-search-results-decoration\s*\{[\s\S]*display: none;/u);
  assert.match(cssSource, /\.query-search-form \.clear-query-button\s*\{[\s\S]*position: static;[\s\S]*width: 28px;[\s\S]*height: 28px;/u);
  assert.doesNotMatch(indexSource, /id="searchDialog"|id="filterDialog"|id="filterInput"/u);
  assert.doesNotMatch(indexSource, /id="detailDialog"/u);
  assert.match(indexSource, /id="activeQueryStrip"/u);
  assert.match(indexSource, /<title>YouTube 歌枠歌曲排行<\/title>/u);
  assert.match(indexSource, /id="status" hidden aria-hidden="true"/u);
  assert.doesNotMatch(indexSource, /class="topbar"|class="topbar-inner"|<h1>Daily Song List<\/h1>|歌曲时间戳排行/u);
  assert.doesNotMatch(indexSource, /class="controls-primary"|class="mobile-toolbar-actions"|class="controls-secondary"/u);
  assert.match(indexSource, /class="controls-inner"[\s\S]*class="[^"]*range-mode[^"]*"[\s\S]*class="[^"]*view-mode[^"]*"[\s\S]*id="querySearchForm"/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.controls-inner\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto;/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.mobile-bottom-nav[\s\S]*grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/u);
  assert.match(cssSource, /\.bottom-nav-icon-wrap\s*\{[\s\S]*width: 32px;[\s\S]*height: 24px;/u);
  assert.match(cssSource, /\.bottom-nav-icon-wrap svg\s*\{[\s\S]*width: 19px;[\s\S]*height: 19px;/u);
  assert.match(cssSource, /\.bottom-nav-item\.active \.bottom-nav-icon-wrap,[\s\S]*\.bottom-nav-item\[aria-current="page"\] \.bottom-nav-icon-wrap\s*\{[\s\S]*background: var\(--accent-soft\);/u);
  assert.doesNotMatch(cssSource, /@media \(max-width: 620px\)/u);
});

test("URL state and query draft are wired while visible share actions are removed", () => {
  assert.match(appSource, /trend:\s*"all"/u);
  assert.match(appSource, /minCount:\s*1/u);
  assert.match(appSource, /sharedUrlApplied:\s*false/u);
  assert.match(appSource, /validTrendFilters: Object\.keys\(TREND_FILTERS\)/u);
  assert.match(appSource, /validMinCounts: MIN_COUNT_OPTIONS/u);
  assert.match(appSource, /function makeQueryDraftFromState/u);
  assert.match(appSource, /function applyQueryDraft/u);
  assert.match(appSource, /function readQueryDraftFromControls[\s\S]*q: els\.queryInput\?\.value/u);
  assert.match(appSource, /FrontendUtils\.activeQueryConditionCount/u);
  assert.match(appSource, /urlParams\.get\("shared"\) === "1"/u);
  assert.doesNotMatch(appSource, /URL state is intentionally read-only/u);
  assert.match(appSource, /FrontendUtils\.serializeUrlState/u);
  assert.doesNotMatch(indexSource, /id="shareButton"|data-copy-link/u);
  assert.doesNotMatch(appSource, /function buildShareUrl|function shareCurrentLink|function copyCurrentLink|navigator\.share|dataset\.copyLink/u);
  assert.doesNotMatch(cssSource, /share-button/u);
});

test("source drawer is inline, grouped, and visible on mobile", () => {
  assert.doesNotMatch(appSource, /DETAIL_BATCH_SIZE|data-open-detail|function renderDetailSources|openDetail\(/u);
  assert.match(appSource, /toggleSourceDrawer\(sourceToggle\.closest\("\.rank-row, \.index-row"\)\)/u);
  assert.match(appSource, /FrontendUtils\.groupOccurrencesByVideo\(occurrences\)/u);
  assert.match(appSource, /const SOURCE_TIMESTAMP_INITIAL_LIMIT = 1/u);
  assert.match(appSource, /className = "source-video-thumb-link"/u);
  assert.match(appSource, /className = "source-inline-thumb source-link"/u);
  assert.match(appSource, /thumb\.tabIndex = -1/u);
  assert.match(appSource, /className = "source-inline-meta"/u);
  assert.match(appSource, /renderSourceTimestampLink\(firstOccurrence, "source-inline-time"\)/u);
  assert.doesNotMatch(appSource, /className = "source-inline-time-overlay"/u);
  assert.match(appSource, /createThumbnailImage\(\{ \.\.\.item, videoId, thumbnailUrl: item\.thumbnailUrl \|\| group\.thumbnailUrl \}, "source-inline-thumb-image"[\s\S]*preferCompact: true/u);
  assert.match(appSource, /priorityMedia: priorityInlineMedia/u);
  assert.match(appSource, /priority: options\.priorityMedia \? "high" : "auto"/u);
  assert.match(appSource, /img\.loading = highPriority \? "eager" : "lazy"/u);
  assert.match(appSource, /img\.fetchPriority = highPriority \? "high" : "low"/u);
  assert.match(appSource, /className = "source-time-extra-toggle"/u);
  assert.match(appSource, /function renderCopySetlistIconButton/u);
  assert.match(appSource, /function createThumbnailImage/u);
  assert.match(appSource, /item\.videoThumbnailUrl/u);
  assert.match(appSource, /img\.hidden = true/u);
  assert.doesNotMatch(appSource, /return uniqueStrings\(\[\.\.\.preferred, placeholderThumbnail\(\)\]\)/u);
  assert.doesNotMatch(appSource, /maxresdefault/u);
  assert.match(appSource, /const RESPONSIVE_BREAKPOINTS = \{[\s\S]*mobileMax: 720,[\s\S]*tabletMax: 919/u);
  assert.match(appSource, /const SOURCE_INLINE_LIMITS = \{[\s\S]*mobile: 2,[\s\S]*tablet: 3,[\s\S]*desktop: 3/u);
  assert.doesNotMatch(appSource, /SOURCE_GROUP_LIMITS/u);
  assert.match(appSource, /function getResponsiveMode/u);
  assert.match(appSource, /window\.matchMedia\?\.\(`\(max-width: \$\{RESPONSIVE_BREAKPOINTS\.mobileMax\}px\)`\)\?\.matches/u);
  assert.match(appSource, /window\.matchMedia\?\.\(`\(max-width: \$\{RESPONSIVE_BREAKPOINTS\.tabletMax\}px\)`\)\?\.matches/u);
  assert.match(appSource, /function isCompactRankMode/u);
  assert.doesNotMatch(appSource, /function sourceInitialLimitForMode/u);
  assert.match(appSource, /function sourceInlineLimitForMode/u);
  assert.doesNotMatch(appSource, /function sourceBatchSizeForMode/u);
  assert.match(appSource, /shouldKeepSingleDrawerOpen\(\)/u);
  assert.doesNotMatch(appSource, /SOURCE_EXPAND_CHUNK_SIZE|convertSourceGroupMoreToCollapse|data-toggle-source-groups|function expandSourceVideoGroups/u);
  assert.match(appSource, /appendSourceGroupRange\(drawer, groups, 0, visibleCount\)/u);
  assert.match(appSource, /document\.createDocumentFragment\(\)/u);
  assert.doesNotMatch(appSource, /查看更多 \$\{remaining\}个来源/u);
  assert.match(appSource, /dataset\.collapseSource = "true"/u);
  assert.match(appSource, /dataset\.copySongLinks = "true"/u);
  assert.match(appSource, /buildSongSourceLinksText\(occurrences\)/u);
  assert.match(appSource, /className = "source-drawer-toolbar"/u);
  assert.match(appSource, /renderSourceCollapseButton\(drawer\.id, drawer\.dataset\.sourceMode \|\| "song", "source-collapse-top ui-chip"\)/u);
  assert.match(appSource, /复制全部链接/u);
  assert.match(appSource, /function renderRankRecord[\s\S]*row\.append\(\s*renderSourceInlineStrip/u);
  assert.match(appSource, /function renderIndexRecord[\s\S]*row\.append\(\s*renderSourceInlineStrip/u);
  assert.doesNotMatch(functionBody("function renderRecordContent"), /renderSourceInlineStrip/u);
  assert.match(appSource, /if \(nextExpanded && shouldKeepSingleDrawerOpen\(\)\) closeOtherMobileSourceDrawers\(row\)/u);
  assert.doesNotMatch(appSource, /data-toggle-artist-sources|ARTIST_SOURCE_INITIAL_LIMIT/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.rank-row\s*\{[\s\S]*"rank content side"[\s\S]*"\. sources sources"[\s\S]*"drawer drawer drawer"/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.rank-header\s*\{[\s\S]*display: none/u);
  assert.match(cssSource, /\.source-inline-strip\s*\{[\s\S]*grid-area: sources;/u);
  assert.match(cssSource, /\.source-inline-thumb\s*\{[\s\S]*width: 56px;[\s\S]*height: 32px;[\s\S]*border-radius: 6px;/u);
  assert.match(cssSource, /\.source-inline-thumb-image\s*\{[\s\S]*object-fit: cover;/u);
  assert.doesNotMatch(cssSource, /\.source-inline-time-overlay/u);
  assert.match(cssSource, /\.source-inline-main\s*\{[\s\S]*grid-template-rows: auto auto;[\s\S]*gap: 1px;/u);
  assert.match(cssSource, /\.source-inline-meta\s*\{[\s\S]*display: inline-flex;[\s\S]*gap: 4px;/u);
  assert.match(cssSource, /\.source-inline-time,[\s\S]*\.source-inline-extra-time,[\s\S]*\.source-inline-time-more\s*\{[\s\S]*background: transparent;[\s\S]*font-variant-numeric: tabular-nums;/u);
  assert.match(cssSource, /\.source-inline-tail\s*\{[\s\S]*display: contents;/u);
  assert.match(cssSource, /\.source-drawer\s*\{[\s\S]*grid-area: drawer;/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.source-drawer\s*\{[\s\S]*width: 100%;[\s\S]*min-width: 0;/u);
  assert.doesNotMatch(cssSource, /@media \(max-width: 720px\)[\s\S]*\.source-drawer\s*\{[^}]*display: none/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.rank-count\.is-strong\s*\{[\s\S]*background: transparent;[\s\S]*color: var\(--muted\);/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.index-toolbar\s*\{[\s\S]*position: static;[\s\S]*top: auto;/u);
  assert.match(cssSource, /\.rank-row::before\s*\{[\s\S]*grid-area: rank;/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.rank-row::before\s*\{[\s\S]*display: none;/u);
  assert.match(cssSource, /\.query-count\[hidden\]\s*\{[\s\S]*display: none;/u);
  assert.doesNotMatch(cssSource, /\.query-trigger\.has-active-query::after/u);
});

test("VTuber rows render display images without default avatar fallback", () => {
  assert.match(appSource, /function renderVtuberDisplayImage/u);
  assert.match(appSource, /window\.FrontendUtils\.vtuberDisplayImageModel\(record \|\| \{\}\)/u);
  assert.match(appSource, /vtuber-display-image-thumbnail/u);
  assert.match(cssSource, /\.vtuber-display-image-thumbnail\s*\{[\s\S]*border-radius: var\(--radius-thumbnail\);/u);
  assert.doesNotMatch(appSource, /fallback-avatar/u);
  assert.doesNotMatch(cssSource, /fallback-avatar/u);
});

test("high-density rank and source rules are encoded in css and browser checks", () => {
  assert.match(cssSource, /--radius-control:\s*8px/u);
  assert.match(cssSource, /--control-compact:\s*36px/u);
  assert.match(cssSource, /--control-default:\s*38px/u);
  assert.match(cssSource, /--control-large:\s*40px/u);
  assert.match(cssSource, /--rank-leading-width:\s*44px/u);
  assert.match(cssSource, /--rank-side-width-mobile:\s*66px/u);
  assert.match(cssSource, /--rank-side-width-tablet:\s*76px/u);
  assert.match(cssSource, /--rank-side-width-desktop:\s*104px/u);
  assert.match(cssSource, /--rank-columns:\s*48px minmax\(0, 1fr\) var\(--rank-side-width-desktop\)/u);
  assert.match(cssSource, /input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\)/u);
  assert.match(cssSource, /\.query-toggle\s*\{[\s\S]*align-items: center;[\s\S]*min-height: 34px;[\s\S]*border-radius: var\(--radius-control\);/u);
  assert.doesNotMatch(indexSource, /class="query-tabs"|data-query-panel-tab=|id="querySearchPanel"|id="queryFilterPanel"/u);
  assert.match(indexSource, /class="query-field-menu-panel"[\s\S]*name="searchField" value="title"[\s\S]*name="searchField" value="artist"[\s\S]*name="searchField" value="channel"[\s\S]*name="searchField" value="video"/u);
  assert.match(cssSource, /\.query-field-menu-panel label\.is-selected\s*\{[\s\S]*background: var\(--accent-soft\);/u);
  assert.match(indexSource, /<\/div>\s*<footer class="query-panel-footer">/u);
  assert.doesNotMatch(indexSource, /<\/div>\s*<\/div>\s*<footer class="query-panel-footer">/u);
  assert.doesNotMatch(indexSource, /class="query-tabs"|data-query-panel-tab=/u);
  assert.doesNotMatch(indexSource, /recentSearchSection|recentSearches|clearRecentSearchesButton|最近搜索/u);
  assert.doesNotMatch(appSource, /RECENT_SEARCHES_KEY|readRecentSearches|writeRecentSearches|renderRecentSearches/u);
  assert.match(cssSource, /\.query-form-grid\s*\{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);[\s\S]*gap: var\(--query-grid-gap\);/u);
  assert.match(cssSource, /\.query-sort-field\s*\{[\s\S]*grid-column: 1 \/ -1;/u);
  assert.match(cssSource, /\.query-segmented\s*\{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(78px, 1fr\)\);/u);
  assert.match(cssSource, /\.query-filter-matrix > \.query-compact-field\s*\{[\s\S]*grid-template-columns: 1fr;[\s\S]*align-items: stretch;/u);
  assert.match(cssSource, /\.query-compact-field\s*\{[\s\S]*grid-template-rows: auto var\(--control-default\);/u);
  assert.match(cssSource, /\.query-panel-footer\s*\{[\s\S]*display: grid;[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/u);
  assert.doesNotMatch(cssSource, /grid-template-columns: auto auto;[\s\S]*justify-content: space-between/u);
  assert.doesNotMatch(indexSource, /query-quick-toggles|query-compact-fields|query-context-fields|query-metric-control/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.query-panel\s*\{[\s\S]*height: min\(calc\(var\(--visual-viewport-height\) - 8px\), 92dvh\);[\s\S]*max-height: min\(calc\(var\(--visual-viewport-height\) - 8px\), 92dvh\);/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.query-panel-body\s*\{[\s\S]*padding-top: 8px;[\s\S]*padding-bottom: 12px;/u);
  assert.match(cssSource, /\.query-panel-body\s*\{[\s\S]*display: grid;[\s\S]*gap: var\(--space-3\);/u);
  assert.match(cssSource, /\.query-filter-matrix\s*\{/u);
  assert.doesNotMatch(cssSource, /\.query-tabs\b|\.query-tab\s*\{|\.query-tab\[|\.query-tab-panel\b|\.query-panel\.is-filter-tab/u);
  assert.doesNotMatch(cssSource, /\.query-panel\.is-filter-tab \.query-panel-body\s*\{[\s\S]*144px/u);
  assert.match(captureSource, /async function assertQueryHistoryPanelSpacing/u);
  assert.match(captureSource, /query history overlaps footer/u);
  assert.doesNotMatch(captureSource, /dailySongList\.recentSearches|mobile-query-recent\.png|query-history-section\[open\]/u);
  assert.doesNotMatch(appSource, /function setQueryPanelTab|queryTabButtons|queryTabPanels/u);
  assert.match(cssSource, /\.rank-row\s*\{[\s\S]*"rank content side"[\s\S]*"\. sources sources"[\s\S]*"\. drawer drawer"/u);
  assert.match(appSource, /const VIEW_RANK_METRIC_ORDER = \{[\s\S]*vtuberRank: \["occurrences", "songs", "videos"\]/u);
  assert.match(appSource, /function renderVtuberAvatar/u);
  assert.match(appSource, /FrontendUtils\.vtuberDisplayImageModel\(record \|\| \{\}\)/u);
  assert.match(appSource, /function renderVtuberChannelTextLink/u);
  assert.match(appSource, /wrapVtuberChannelLink\(media, record \|\| \{\}, "vtuber-display-link"\)/u);
  assert.match(appSource, /function vtuberChannelUrlCandidate/u);
  assert.match(appSource, /function vtuberChannelUrlCandidate[\s\S]*item\.sourceUrl/u);
  assert.match(appSource, /function vtuberChannelUrlCandidate[\s\S]*item\.sourceUrls/u);
  assert.match(appSource, /function renderVtuberCollectionBadge/u);
  assert.match(appSource, /FrontendUtils\.vtuberCollectionBadgeModel\(record \|\| \{\}\)/u);
  const vtuberTitleLineBlock = cssBlock(".vtuber-title-line");
  assert.match(vtuberTitleLineBlock, /display: contents;/u);
  assert.doesNotMatch(vtuberTitleLineBlock, /grid-template-columns/u);
  assert.match(cssSource, /\.vtuber-display-image\s*\{[\s\S]*width: 44px;[\s\S]*height: 44px;/u);
  assert.match(cssSource, /\.vtuber-display-link\s*\{[\s\S]*grid-area: image;[\s\S]*width: 44px;[\s\S]*height: 44px;/u);
  assert.match(cssSource, /\.vtuber-title-link:hover\s*\{[\s\S]*text-decoration: underline;/u);
  assert.match(cssSource, /@media \(min-width: 721px\) and \(max-width: 919px\)[\s\S]*\.rank-row\s*\{[\s\S]*"rank content side"[\s\S]*"\. sources sources"[\s\S]*"drawer drawer drawer"/u);
  assert.match(cssSource, /\.rank-side-top\s*\{[\s\S]*display: inline-flex;[\s\S]*justify-content: flex-end;/u);
  assert.match(cssSource, /\.rank-side-trend\[aria-hidden="true"\]\s*\{[\s\S]*display: none;/u);
  assert.doesNotMatch(cssSource, /\.rank-actions-line|\.rank-trend-inline|\.rank-trend\s*\{/u);
  assert.match(cssSource, /@media \(min-width: 721px\) and \(max-width: 919px\)[\s\S]*\.rank-subline\s*\{[\s\S]*display: flex;[\s\S]*white-space: nowrap;/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.rank-subline\s*\{[\s\S]*display: flex;[\s\S]*white-space: nowrap;/u);
  assert.match(cssSource, /\.rank-expand::after\s*\{[\s\S]*border-right: 1\.5px solid currentcolor;[\s\S]*transform: translateY\(-1px\) rotate\(45deg\);/u);
  assert.match(cssSource, /\.rank-expand\[aria-expanded="true"\]::after\s*\{[\s\S]*rotate\(225deg\)/u);
  assert.match(cssSource, /\.source-copy-icon\s*\{[\s\S]*width: var\(--chip-icon-size\);[\s\S]*padding: 0;/u);
  assert.match(appSource, /function renderSourceVideoGroup[\s\S]*channel\.setAttribute\("aria-label", channelLink\.isFallbackSearch/u);
  assert.match(appSource, /function renderSourceVideoGroup[\s\S]*channel\.title = channelLink\.isFallbackSearch/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.source-inline-strip \.source-inline-thumb\.source-link\s*\{[\s\S]*width: 56px;[\s\S]*height: 32px;/u);
  assert.match(cssSource, /@media \(max-width: 340px\)[\s\S]*\.source-inline-strip \.source-inline-thumb\.source-link\s*\{[\s\S]*width: 48px;[\s\S]*height: 27px;/u);
  assert.doesNotMatch(cssSource, /\.source-copy-icon span|ui-chip-icon-label/u);
  assert.match(cssSource, /\.trend-badge\s*\{[\s\S]*min-height: 20px;[\s\S]*font-size: 10\.5px;[\s\S]*white-space: nowrap;/u);
  assert.match(cssSource, /\.trend-up,[\s\S]*\.trend-increase,[\s\S]*\.trend-new/u);
  assert.match(appSource, /FrontendUtils\.trendDisplayModel\(trend\)/u);
  assert.doesNotMatch(appSource, /formatCompactSignedDelta|formatSignedDelta/u);
  assert.doesNotMatch(functionBody("function renderCopySetlistButton"), /textContent = label/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.source-drawer\s*\{[\s\S]*gap: 0;/u);
  assert.match(cssSource, /\.source-video-group\s*\{[\s\S]*grid-template-areas: "thumb main copy"/u);
  assert.match(cssSource, /\.source-video-thumb-link\s*\{[\s\S]*aspect-ratio: 16 \/ 9/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.source-video-group\s*\{[\s\S]*grid-template-columns: 64px minmax\(0, 1fr\) 28px;[\s\S]*padding: 6px 0;/u);
  assert.match(cssSource, /\.source-video-channel\s*\{[\s\S]*font-size: 13px;[\s\S]*font-weight: 600;/u);
  assert.match(cssSource, /\.source-video-title\s*\{[\s\S]*font-size: 12\.5px;[\s\S]*font-weight: 500;/u);
  assert.match(cssSource, /\.source-video-title\s*\{[\s\S]*text-decoration: none;/u);
  assert.match(cssSource, /\.source-video-channel:hover,[\s\S]*\.source-video-title:hover\s*\{[\s\S]*text-decoration: underline;/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.video-card,[\s\S]*\.video-compact \.video-card\s*\{[\s\S]*grid-template-columns: clamp\(120px, 34vw, 144px\) minmax\(0, 1fr\);/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.video-body,[\s\S]*\.video-compact \.video-body\s*\{[\s\S]*display: contents;/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.song-list,[\s\S]*\.video-compact \.song-list\s*\{[\s\S]*grid-column: 1 \/ -1;/u);
  assert.match(cssSource, /\.video-grid\s*\{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(280px, 1fr\)\);/u);
  assert.match(appSource, /className = "video-more video-more-top"/u);
  assert.match(cssSource, /@media \(max-width: 340px\)[\s\S]*--source-thumb-width: var\(--source-thumb-width-narrow\)/u);
  assert.match(verifySource, /async function mobileFilterSheetFlow/u);
  assert.match(verifySource, /async function waitForQueryFilterControls/u);
  assert.match(verifySource, /details:not\(\[open\]\)/u);
  assert.match(verifySource, /async function mobileRankVisualGeometry/u);
  assert.match(verifySource, /async function mobileCopyAllLinksFlow/u);
  assert.match(verifySource, /async function mobileVideoCardGeometry/u);
  assert.match(verifySource, /async function desktopRankVisualGeometry/u);
  assert.match(verifySource, /async function compactSourceDrawerFlow/u);
  assert.match(verifySource, /query-panel-bottom-\$\{viewport\.join\("x"\)\}\.png/u);
  assert.match(verifySource, /rank-expanded-trend-\$\{viewport\.join\("x"\)\}\.png/u);
});

test("mobile source preview contract matches compact documentation", () => {
  const readmeSource = fs.readFileSync(path.join(__dirname, "..", "README.md"), "utf8");
  const specSource = fs.readFileSync(path.join(__dirname, "..", "docs", "ui-spec.md"), "utf8");
  assert.match(appSource, /SOURCE_INLINE_LIMITS\s*=\s*\{[\s\S]*mobile: 2,[\s\S]*tablet: 3,[\s\S]*desktop: 3,/u);
  assert.match(readmeSource, /Mobile three-source row with two inline thumbnails and one compact view-all action/u);
  assert.match(specSource, /3 个唯一来源视频：移动端默认内联前 2 个真实来源/u);
  assert.doesNotMatch(readmeSource, /Mobile three source inline row with thumbnail tail action/u);
  assert.doesNotMatch(specSource, /3 个唯一来源视频：手机两列布局/u);
});

test("desktop and tablet contracts use explicit responsive layout", () => {
  assert.match(cssSource, /@media \(min-width: 920px\) and \(max-width: 1279px\)[\s\S]*\.controls-inner\s*\{[\s\S]*grid-template-columns: auto minmax\(280px, 1fr\) minmax\(260px, 380px\);/u);
  assert.doesNotMatch(cssSource, /grid-template-columns: auto minmax\(0, 1fr\) auto auto minmax\(220px, 1\.1fr\) minmax\(108px, 140px\) minmax\(160px, 220px\)/u);
  assert.match(cssSource, /@media \(min-width: 1280px\)[\s\S]*\.controls-inner\s*\{[\s\S]*grid-template-columns: auto auto minmax\(340px, 480px\);/u);
  assert.match(cssSource, /@media \(min-width: 721px\) and \(max-width: 919px\)[\s\S]*--rank-columns: 42px minmax\(0, 1fr\) var\(--rank-side-width-tablet\)/u);
  assert.match(cssSource, /@media \(min-width: 721px\) and \(max-width: 919px\)[\s\S]*\.controls-inner\s*\{[\s\S]*grid-template-columns: auto minmax\(0, 1fr\) minmax\(220px, 320px\);/u);
  assert.match(appSource, /mode === "mobile"[\s\S]*variant === "top"[\s\S]*renderMobileTopPagination\(pageInfo\)/u);
  assert.match(appSource, /function renderPageJumpControl\(pageInfo\)/u);
  assert.match(appSource, /input\.dataset\.pageInput = "true"/u);
  assert.match(appSource, /dataPageJumpForm|data-page-jump-form|pageJumpForm/u);
  assert.match(cssSource, /\.page-jump\s*\{[\s\S]*display: inline-flex;/u);
});

test("search suggestions highlight safely without assigning untrusted innerHTML", () => {
  const highlightBody = functionBody("function appendHighlightedText");
  assert.match(highlightBody, /document\.createElement\("mark"\)/u);
  assert.match(highlightBody, /mark\.textContent/u);
  assert.doesNotMatch(highlightBody, /innerHTML/u);
  assert.doesNotMatch(indexSource, /最近搜索|recentSearch/u);
});

test("latest runtime uses request pagination instead of loading every page shard", () => {
  assert.match(appSource, /function requestRuntimeMeta/u);
  assert.match(appSource, /function canUseRequestRuntime/u);
  assert.match(appSource, /async function requestViewPage/u);
  assert.match(appSource, /buildRequestPageKey/u);
  assert.match(appSource, /AbortController/u);
  assert.match(appSource, /scheduleAdjacentRequestPagePrefetch/u);
  assert.match(appSource, /loadRequestSearchRecords/u);
  assert.match(appSource, /requestSearchBucket\(query\)/u);
  assert.match(appSource, /loadRequestDetailRecords/u);
  assert.match(appSource, /sourceDetailKey/u);
  assert.doesNotMatch(appSource, /Promise\.all\(\s*pages\.map/u);
  assert.doesNotMatch(appSource, /pagePayloads\.flatMap/u);
  assert.doesNotMatch(appSource, /complete all runtime/i);
});

test("range cache song records are lazy getters", () => {
  assert.match(appSource, /defineLazySongCache\(cache, "allSongRecords"/u);
  assert.match(appSource, /defineLazySongCache\(cache, "nicheSongRecords"/u);
  assert.match(appSource, /defineLazySongCache\(cache, "visibleSongRecords"/u);
  assert.match(appSource, /defineLazySongCache\(cache, "visibleNicheSongRecords"/u);
  assert.doesNotMatch(functionBody("function createRangeCache"), /buildSongRecords/u);
});

test("mobile summary and pagination have compact rules", () => {
  assert.doesNotMatch(appSource, /summary-range/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.summary-actions\s*\{[\s\S]*display: flex;[\s\S]*overflow-x: auto;/u);
  assert.match(cssSource, /\.summary\s*\{[\s\S]*grid-template-areas:[\s\S]*"main actions"[\s\S]*"note note"/u);
  assert.match(cssSource, /@media \(max-width: 720px\)[\s\S]*\.summary\s*\{[\s\S]*grid-template-areas:[\s\S]*"main"[\s\S]*"note"/u);
  assert.match(cssSource, /\.summary-actions\s*\{[\s\S]*grid-area: actions;[\s\S]*margin-left: 0;/u);
  assert.match(appSource, /summary-metrics/u);
  assert.match(appSource, /function compactSummaryMetrics/u);
  assert.match(appSource, /function compactSummaryNote/u);
  assert.doesNotMatch(functionBody("function compactSummaryMetrics"), /首结果/u);
  assert.match(functionBody("function compactSummaryMetrics"), /首歌曲\|首小众歌曲\|位歌手\|个频道\|个小众歌曲频道\|歌曲收录\|小众歌曲收录\|个视频/u);
  assert.match(functionBody("function compactSummaryNote"), /已隐藏无歌手/u);
  assert.match(functionBody("function renderActiveQueryStrip"), /if \(items\.length >= 2\)/u);
  assert.match(functionBody("function renderActiveQueryStrip"), /清除全部筛选条件/u);
  assert.match(appSource, /variant === "top"[\s\S]*`\$\{pageInfo\.startIndex \+ 1\}-\$\{pageInfo\.endIndex\} \/ \$\{pageInfo\.total\}/u);
  assert.match(appSource, /function paginationTokenOptions/u);
  assert.match(appSource, /renderPageButton\("上一页"[\s\S]*\{ icon: "prev" \}/u);
  assert.match(appSource, /renderPageButton\("下一页"[\s\S]*\{ icon: "next" \}/u);
  assert.doesNotMatch(appSource, /if \(!compactTop\) controls\.append\(renderPageJumpControl\(pageInfo\)\)/u);
  assert.match(appSource, /function renderPageSelectControl/u);
  assert.match(appSource, /function renderMobileTopPagination/u);
  assert.match(appSource, /function renderMobileBottomPagination/u);
  assert.match(appSource, /function renderPageEllipsisToken/u);
  assert.doesNotMatch(appSource, /function renderPageJumpToken|data-page-jump-direction/u);
});

test("rank summaries keep metrics to entity count and song collections", () => {
  const songRankBody = functionBody("function renderSongRank");
  const artistRankBody = functionBody("function renderArtistRank");
  const vtuberRankBody = functionBody("function renderVtuberRank");
  const songIndexBody = functionBody("function renderSongIndexView");
  assert.doesNotMatch(songRankBody, /summaryVideoMetric\(rangeCache, selection\)/u);
  assert.doesNotMatch(artistRankBody, /metric\(selection\.videoCount, "个视频"\)/u);
  assert.doesNotMatch(vtuberRankBody, /metric\(selection\.videoCount, "条歌曲收录"\)/u);
  assert.match(songIndexBody, /summaryVideoMetric\(rangeCache, selection\)/u);
  assert.doesNotMatch(songRankBody, /metric\(selection\.videoCount, "个视频"\)/u);
  assert.doesNotMatch(songIndexBody, /metric\(selection\.videoCount, "个视频"\)/u);
  assert.match(functionBody("function occurrenceVisibilityMetric"), /歌曲收录/u);
  assert.match(appSource, /function summaryVideoCountModel\(rangeCache, selection\)[\s\S]*visibleCount: selection\?\.videoCount,[\s\S]*sourceCount: sourceVideoCountForSummary\(rangeCache\)/u);
  assert.match(appSource, /function sourceVideoCountForSummary\(rangeCache\)[\s\S]*rangeCache\.items\.length/u);
  assert.match(appSource, /function summaryNote\(selection, extra = "", rangeCache = null\)[\s\S]*summaryVideoVisibilityNote\(rangeCache, selection\)/u);
});

test("VTuber channel expansion renders paged song groups before source pages", () => {
  const vtuberRankBody = functionBody("function renderVtuberRank");
  const songSourceBody = functionBody("async function toggleArtistSongSource");
  const sourcePageBody = functionBody("async function setSourceDrawerPage");
  const songGroupBody = functionBody("function renderArtistSongGroup");
  assert.match(vtuberRankBody, /getSongGroups: \(\) => getVtuberSongGroups\(record\)/u);
  assert.match(appSource, /function renderRequestedPageResult[\s\S]*mode: "vtuber"[\s\S]*getSongGroups: \(\) => getVtuberSongGroups\(record\)/u);
  assert.match(appSource, /function completeSongGroupsForDrawer\(occurrences, fallbackGroups = \[\], mode = ""\)[\s\S]*buildArtistSongGroups\(filterDisplaySongOccurrences\(occurrences \|\| \[\]\)\)[\s\S]*mode === "vtuber"[\s\S]*completeGroups\.length < fallbackGroups\.length/u);
  assert.match(appSource, /async function setSourceDrawerExpanded[\s\S]*songGroups = completeSongGroupsForDrawer\(visibleOccurrences, songGroups, mode\)/u);
  assert.match(songGroupBody, /artistLabelForSongGroup\(group\)/u);
  assert.match(songGroupBody, /artistSongCountLabel\(group\)/u);
  assert.match(songSourceBody, /sourceDetailPageForContainer\(sources, sources\._sourceOccurrences \|\| \[\]/u);
  assert.match(songSourceBody, /groups: pageState\.groups,[\s\S]*pageInfo: pageState\.pageInfo/u);
  assert.match(sourcePageBody, /drawer\.dataset\.sourceMode === "artist-song" \? drawer : row/u);
  assert.match(sourcePageBody, /sourceDetailPageForContainer\(sourceContainer, sourceContainer\._sourceDetailOccurrences \|\| sourceContainer\._sourceOccurrences \|\| \[\]/u);
  assert.match(cssSource, /\.artist-song-artist\s*\{[\s\S]*text-overflow: ellipsis;[\s\S]*white-space: nowrap;/u);
});

function functionBody(signature) {
  const start = appSource.indexOf(signature);
  assert.notEqual(start, -1, `missing ${signature}`);
  const braceStart = appSource.indexOf("{", start);
  let depth = 0;
  for (let index = braceStart; index < appSource.length; index += 1) {
    const char = appSource[index];
    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;
    if (depth === 0) return appSource.slice(braceStart, index + 1);
  }
  throw new Error(`unterminated ${signature}`);
}
